/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: spec.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "spec.pb-c.h"
void   fields_t__init
                     (FieldsT         *message)
{
  static const FieldsT init_value = FIELDS_T__INIT;
  *message = init_value;
}
size_t fields_t__get_packed_size
                     (const FieldsT *message)
{
  assert(message->base.descriptor == &fields_t__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t fields_t__pack
                     (const FieldsT *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &fields_t__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t fields_t__pack_to_buffer
                     (const FieldsT *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &fields_t__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
FieldsT *
       fields_t__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (FieldsT *)
     protobuf_c_message_unpack (&fields_t__descriptor,
                                allocator, len, data);
}
void   fields_t__free_unpacked
                     (FieldsT *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &fields_t__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ast_node_t__init
                     (AstNodeT         *message)
{
  static const AstNodeT init_value = AST_NODE_T__INIT;
  *message = init_value;
}
size_t ast_node_t__get_packed_size
                     (const AstNodeT *message)
{
  assert(message->base.descriptor == &ast_node_t__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ast_node_t__pack
                     (const AstNodeT *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ast_node_t__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ast_node_t__pack_to_buffer
                     (const AstNodeT *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ast_node_t__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
AstNodeT *
       ast_node_t__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (AstNodeT *)
     protobuf_c_message_unpack (&ast_node_t__descriptor,
                                allocator, len, data);
}
void   ast_node_t__free_unpacked
                     (AstNodeT *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &ast_node_t__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   element__init
                     (Element         *message)
{
  static const Element init_value = ELEMENT__INIT;
  *message = init_value;
}
size_t element__get_packed_size
                     (const Element *message)
{
  assert(message->base.descriptor == &element__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t element__pack
                     (const Element *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &element__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t element__pack_to_buffer
                     (const Element *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &element__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Element *
       element__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Element *)
     protobuf_c_message_unpack (&element__descriptor,
                                allocator, len, data);
}
void   element__free_unpacked
                     (Element *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &element__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   page_t__init
                     (PageT         *message)
{
  static const PageT init_value = PAGE_T__INIT;
  *message = init_value;
}
size_t page_t__get_packed_size
                     (const PageT *message)
{
  assert(message->base.descriptor == &page_t__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t page_t__pack
                     (const PageT *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &page_t__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t page_t__pack_to_buffer
                     (const PageT *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &page_t__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
PageT *
       page_t__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (PageT *)
     protobuf_c_message_unpack (&page_t__descriptor,
                                allocator, len, data);
}
void   page_t__free_unpacked
                     (PageT *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &page_t__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   response__init
                     (Response         *message)
{
  static const Response init_value = RESPONSE__INIT;
  *message = init_value;
}
size_t response__get_packed_size
                     (const Response *message)
{
  assert(message->base.descriptor == &response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t response__pack
                     (const Response *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t response__pack_to_buffer
                     (const Response *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Response *
       response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Response *)
     protobuf_c_message_unpack (&response__descriptor,
                                allocator, len, data);
}
void   response__free_unpacked
                     (Response *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor fields_t__field_descriptors[4] =
{
  {
    "integerValue",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(FieldsT, integervalue),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "doubleValue",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(FieldsT, doublevalue),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "booleanValue",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(FieldsT, booleanvalue),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "stringValue",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(FieldsT, stringvalue),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned fields_t__field_indices_by_name[] = {
  2,   /* field[2] = booleanValue */
  1,   /* field[1] = doubleValue */
  0,   /* field[0] = integerValue */
  3,   /* field[3] = stringValue */
};
static const ProtobufCIntRange fields_t__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor fields_t__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "fields_t",
  "FieldsT",
  "FieldsT",
  "",
  sizeof(FieldsT),
  4,
  fields_t__field_descriptors,
  fields_t__field_indices_by_name,
  1,  fields_t__number_ranges,
  (ProtobufCMessageInit) fields_t__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ast_node_t__field_descriptors[4] =
{
  {
    "left",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(AstNodeT, left),
    &ast_node_t__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "right",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(AstNodeT, right),
    &ast_node_t__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "type",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(AstNodeT, type),
    &node_type_t__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "field",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(AstNodeT, field),
    &fields_t__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ast_node_t__field_indices_by_name[] = {
  3,   /* field[3] = field */
  0,   /* field[0] = left */
  1,   /* field[1] = right */
  2,   /* field[2] = type */
};
static const ProtobufCIntRange ast_node_t__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor ast_node_t__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "astNode_t",
  "AstNodeT",
  "AstNodeT",
  "",
  sizeof(AstNodeT),
  4,
  ast_node_t__field_descriptors,
  ast_node_t__field_indices_by_name,
  1,  ast_node_t__number_ranges,
  (ProtobufCMessageInit) ast_node_t__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor element__field_descriptors[4] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Element, name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "type",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Element, type),
    &element_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "field",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Element, field),
    &fields_t__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "el",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Element, el),
    &element__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned element__field_indices_by_name[] = {
  3,   /* field[3] = el */
  2,   /* field[2] = field */
  0,   /* field[0] = name */
  1,   /* field[1] = type */
};
static const ProtobufCIntRange element__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor element__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "element",
  "Element",
  "Element",
  "",
  sizeof(Element),
  4,
  element__field_descriptors,
  element__field_indices_by_name,
  1,  element__number_ranges,
  (ProtobufCMessageInit) element__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor page_t__field_descriptors[4] =
{
  {
    "timestamp",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(PageT, timestamp),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "name",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(PageT, name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "list",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(PageT, list),
    &element__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "page",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(PageT, page),
    &page_t__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned page_t__field_indices_by_name[] = {
  2,   /* field[2] = list */
  1,   /* field[1] = name */
  3,   /* field[3] = page */
  0,   /* field[0] = timestamp */
};
static const ProtobufCIntRange page_t__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor page_t__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "page_t",
  "PageT",
  "PageT",
  "",
  sizeof(PageT),
  4,
  page_t__field_descriptors,
  page_t__field_indices_by_name,
  1,  page_t__number_ranges,
  (ProtobufCMessageInit) page_t__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor response__field_descriptors[2] =
{
  {
    "result",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Response, result),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "page_list",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Response, page_list),
    &page_t__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned response__field_indices_by_name[] = {
  1,   /* field[1] = page_list */
  0,   /* field[0] = result */
};
static const ProtobufCIntRange response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Response",
  "Response",
  "Response",
  "",
  sizeof(Response),
  2,
  response__field_descriptors,
  response__field_indices_by_name,
  1,  response__number_ranges,
  (ProtobufCMessageInit) response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue node_type_t__enum_values_by_number[26] =
{
  { "SELECT_QUERY_NODE", "NODE_TYPE_T__SELECT_QUERY_NODE", 0 },
  { "INSERT_QUERY_NODE", "NODE_TYPE_T__INSERT_QUERY_NODE", 1 },
  { "UPDATE_QUERY_NODE", "NODE_TYPE_T__UPDATE_QUERY_NODE", 2 },
  { "DELETE_QUERY_NODE", "NODE_TYPE_T__DELETE_QUERY_NODE", 3 },
  { "NESTED_QUERY_NODE", "NODE_TYPE_T__NESTED_QUERY_NODE", 4 },
  { "QUERY_SET_NODE", "NODE_TYPE_T__QUERY_SET_NODE", 5 },
  { "OBJECT_NODE", "NODE_TYPE_T__OBJECT_NODE", 6 },
  { "VALUES_NODE", "NODE_TYPE_T__VALUES_NODE", 7 },
  { "ELEMENT_SET_NODE", "NODE_TYPE_T__ELEMENT_SET_NODE", 8 },
  { "ELEMENT_NODE", "NODE_TYPE_T__ELEMENT_NODE", 9 },
  { "KEY_NODE", "NODE_TYPE_T__KEY_NODE", 10 },
  { "INT_VAL_NODE", "NODE_TYPE_T__INT_VAL_NODE", 11 },
  { "DOUBLE_VAL_NODE", "NODE_TYPE_T__DOUBLE_VAL_NODE", 12 },
  { "BOOL_VAL_NODE", "NODE_TYPE_T__BOOL_VAL_NODE", 13 },
  { "STR_VAL_NODE", "NODE_TYPE_T__STR_VAL_NODE", 14 },
  { "FILTER_NODE", "NODE_TYPE_T__FILTER_NODE", 15 },
  { "OP_EQ_NODE", "NODE_TYPE_T__OP_EQ_NODE", 16 },
  { "OP_NEQ_NODE", "NODE_TYPE_T__OP_NEQ_NODE", 17 },
  { "OP_GT_NODE", "NODE_TYPE_T__OP_GT_NODE", 18 },
  { "OP_GTE_NODE", "NODE_TYPE_T__OP_GTE_NODE", 19 },
  { "OP_LE_NODE", "NODE_TYPE_T__OP_LE_NODE", 20 },
  { "OP_LEE_NODE", "NODE_TYPE_T__OP_LEE_NODE", 21 },
  { "OP_LIKE_NODE", "NODE_TYPE_T__OP_LIKE_NODE", 22 },
  { "OP_AND_NODE", "NODE_TYPE_T__OP_AND_NODE", 23 },
  { "OP_OR_NODE", "NODE_TYPE_T__OP_OR_NODE", 24 },
  { "OP_NOT_NODE", "NODE_TYPE_T__OP_NOT_NODE", 25 },
};
static const ProtobufCIntRange node_type_t__value_ranges[] = {
{0, 0},{0, 26}
};
static const ProtobufCEnumValueIndex node_type_t__enum_values_by_name[26] =
{
  { "BOOL_VAL_NODE", 13 },
  { "DELETE_QUERY_NODE", 3 },
  { "DOUBLE_VAL_NODE", 12 },
  { "ELEMENT_NODE", 9 },
  { "ELEMENT_SET_NODE", 8 },
  { "FILTER_NODE", 15 },
  { "INSERT_QUERY_NODE", 1 },
  { "INT_VAL_NODE", 11 },
  { "KEY_NODE", 10 },
  { "NESTED_QUERY_NODE", 4 },
  { "OBJECT_NODE", 6 },
  { "OP_AND_NODE", 23 },
  { "OP_EQ_NODE", 16 },
  { "OP_GTE_NODE", 19 },
  { "OP_GT_NODE", 18 },
  { "OP_LEE_NODE", 21 },
  { "OP_LE_NODE", 20 },
  { "OP_LIKE_NODE", 22 },
  { "OP_NEQ_NODE", 17 },
  { "OP_NOT_NODE", 25 },
  { "OP_OR_NODE", 24 },
  { "QUERY_SET_NODE", 5 },
  { "SELECT_QUERY_NODE", 0 },
  { "STR_VAL_NODE", 14 },
  { "UPDATE_QUERY_NODE", 2 },
  { "VALUES_NODE", 7 },
};
const ProtobufCEnumDescriptor node_type_t__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "nodeType_t",
  "nodeType_t",
  "NodeTypeT",
  "",
  26,
  node_type_t__enum_values_by_number,
  26,
  node_type_t__enum_values_by_name,
  1,
  node_type_t__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue element_type__enum_values_by_number[4] =
{
  { "INTEGER", "ELEMENT_TYPE__INTEGER", 0 },
  { "FLOAT", "ELEMENT_TYPE__FLOAT", 1 },
  { "BOOLEAN", "ELEMENT_TYPE__BOOLEAN", 2 },
  { "STRING", "ELEMENT_TYPE__STRING", 3 },
};
static const ProtobufCIntRange element_type__value_ranges[] = {
{0, 0},{0, 4}
};
static const ProtobufCEnumValueIndex element_type__enum_values_by_name[4] =
{
  { "BOOLEAN", 2 },
  { "FLOAT", 1 },
  { "INTEGER", 0 },
  { "STRING", 3 },
};
const ProtobufCEnumDescriptor element_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "elementType",
  "elementType",
  "ElementType",
  "",
  4,
  element_type__enum_values_by_number,
  4,
  element_type__enum_values_by_name,
  1,
  element_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
